name: lifelab3
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.4.0+66
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  # flutter_windowmanager: ^0.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  http: ^1.3.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.2
  dio: ^5.3.3
  flutter_svg: ^1.1.6
  firebase_core: ^2.19.0
  pin_code_fields: ^8.0.1
  flutter_overlay_loader: ^2.0.0
  firebase_messaging: ^14.7.5
  path_provider: ^2.1.1
  cached_network_image: ^3.3.0
  permission_handler: ^11.0.1
  open_file: ^3.5.10
  image_picker: ^1.1.2
  lottie: ^2.7.0
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0
  chat_gpt_sdk: ^2.2.5
  flutter_cached_pdfview: ^0.4.2
  video_player: ^2.7.0
  youtube_player_flutter: ^9.1.0
  chewie: ^1.5.0
  webview_flutter: ^4.4.2
  youtube_explode_dart: ^2.0.0
  auto_size_text: ^3.0.0
  new_version_plus: ^0.0.9
  shimmer:
  upgrader: ^9.0.0
  flutter_inappwebview: ^6.1.5
  json_stream: ^1.0.1
  # image_gallery_saver: ^2.0.3
  intl: ^0.20.2
  photo_view: ^0.15.0
  device_info_plus: ^9.1.2
  flutter_local_notifications:
  image_cropper: ^9.1.0
  share_plus: 7.2.1
  persistent_bottom_nav_bar: ^5.0.2
  smooth_page_indicator: ^1.2.1
  mixpanel_flutter: ^2.4.4
  sms_autofill: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd/AvenirLTStd-Black.otf
        - asset: assets/fonts/AvenirLTStd/AvenirLTStd-Book.otf
        - asset: assets/fonts/AvenirLTStd/AvenirLTStd-Medium.otf
          weight: 600
        - asset: assets/fonts/AvenirLTStd/AvenirLTStd-Heavy.otf
          weight: 700
        - asset: assets/fonts/AvenirLTStd/AvenirLTStd-Black.otf
          weight: 800
        - asset: assets/fonts/AvenirLTStd/AvenirLTStd-Roman.otf
          weight: 500



